version: '3.8'

services:
  web-public:
    image: ghcr.io/jmatuszczakk/cwlb-frontend_public:latest
    ports:
      - "80:5000"
  web-panel:
    image: ghcr.io/jmatuszczakk/cwlb-frontend_panel:latest
    ports:
      - "81:8501"
  api:
    image: ghcr.io/jmatuszczakk/cwlb-backend-api:latest
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
