uses: Its4Nik/NGX-action@3.1
  with:
    # Token such as GITHUB_TOKEN that has `write:packages` scope to authenticate against GCHR.
    github-push-secret: {{secrets.MY_SECRET }}
    # Docker Image name
    docker-image-name: ghcr.io/jmatuszczakk/cwlb-frontend_public
    # Docker Image tag
    docker-image-tag: # optional, default is latest
    # Dockerfile path and name
    dockerfile-path: frontent_public/Dockerfile
    # Path to the build context
    build-context: frontend_public
    # If 'true', skip pushing the image
    build-only: # optional, default is false
    # Comma-separated list of build arguments. Must be of the format KEY=VALUE,KEY=VALUE
    docker-build-args: # optional, default is 
